### ISSUE TITLE
Improve search time

### ISSUE THREAD

**Issue by Josh-Lawson** [DigitalDiners/PantryPro#29]
Need to improve search time when searching for recipes

- Can remove recipes that don't have images from database so less recipes to search through
- Possibly remove recipes older than a certain date from database

**Comment by akira-creates** [comment]
Notes:
- Takes around 1minute after clicking "Search Recipes" button to finish the request and show the results.
- Takes the seems to be a bit quicker the more ingredients you add. e.g. 1 ingredients ~1 minute, 4 ingredients is a bit better at ~40 seconds

**Comment by Josh-Lawson** [comment]
- [ ] Use a profiler to find bottleneck of search

**Comment by akira-creates** [comment]
Majority of time when searching appears to take place in process called: "NtWaitForSingleObject"... Not sure what to do with this information
